### ISSUE TITLE
Re-indent breaks lines after Apostrophe ('), changing meaning of code

### ISSUE THREAD

**Issue by cauli** [hundredrabbits/Ronin#101]
<img width="162" alt="Screen Shot 2019-08-02 at 16 38 06" src="https://user-images.githubusercontent.com/284283/62377996-1cf91400-b544-11e9-8e5c-4711db015ec4.png">

**Comment by neauoire** [comment]
yeah, I have to find a way to address that, it's likely that this pattern will have to change.

**Comment by neauoire** [comment]
Removed the `'` syntax from the interpreter.
