### ISSUE TITLE
$path helper not working in Elementary OS

### ISSUE THREAD

**Issue by dualhammers** [hundredrabbits/Ronin#115]
**Expected result**
Per Video Tutorial dragging a file onto the Ronin window with the `$path` command entered should complete a text link for the file path

**Actual result**
Nothing seems to occur.

**OS used**
Elementary OS 5.0 Juno

**Gif example of what is occurring**

![Screen record from 2019-11-07 16 23 15](https://user-images.githubusercontent.com/7495830/68436360-0255bd00-017b-11ea-8eb5-2f01a4449611.gif)

**Comment by neauoire** [comment]
Ah! Excellent, thanks. Just fixed that :) 
Just remember that it's now `(import $path)`, and not `(open $path)`
