### ISSUE TITLE
Open command won't execute

### ISSUE THREAD

**Issue by dualhammers** [hundredrabbits/Ronin#116]
**Expected result**
Per the video tutorial: copying the path name for a file and running the program using the open command will open a file and resize the canvas to fit.

**Actual result**
Nothing occurs

**OS used**
Elementary OS 5.0 Juno

**Video evidence**

![Screen record from 2019-11-07 16 32 48](https://user-images.githubusercontent.com/7495830/68437011-da675900-017c-11ea-9948-e665b355f4ea.gif)

**Comment by neauoire** [comment]
Open has been replaced with import, it is now `(import $path)`
