### ISSUE TITLE
Exporting image seemingly broken

### ISSUE THREAD

**Issue by brubsby** [hundredrabbits/Ronin#118]
I get this error in the console when I try to export image via the cmdorctrl+e shortcut:
![image](https://user-images.githubusercontent.com/57653502/74120504-3cbf6380-4b89-11ea-8488-dce901dbf5b5.png)

Looks like maybe source.download was renamed to source.write, but usages weren't changed.

**Comment by neauoire** [comment]
Ah! yes, it was using the old version of the source lib, thanks for the head's up!
Fixed :)
