### ISSUE TITLE
How to batch process images?

### ISSUE THREAD

**Issue by whatacold** [hundredrabbits/Ronin#127]
Hi,

Ronin is fantastic, it blows my mind, thanks for this piece of software.

I wonder if it's possible to batch process images, for example, below is the `example/pixels/crop.lisp`, is it possible to crop many images using it? If so, how?

    ; crop
    (clear)
    (open $path)
    (crop 
      (rect 100 100 400 400))

**Comment by whatacold** [comment]
Besides, is there any documentation about the Lain dialect? Especially about its APIs.

I found very little at https://wiki.xxiivv.com/site/lain.html, and I wonder if there is a `loop` or `while` control structure, so that it can be easy to do this batch processing.

**Comment by neauoire** [comment]
Hi!

Sure, so make sure you have the latest version(I just pushed a new `(files)` helper that makes this a lot easier)

```
(clear)

(defn print-file 
  (name index) 
  (fill 
    (text 0 
      (add 
        (mul index 40) 50) 40 name) "red"))

(each 
  (files) print-file)
```

![Screenshot from 2020-05-19 07-09-06@2x](https://user-images.githubusercontent.com/1455726/82264307-a5478900-999f-11ea-8077-37ddf58a80d0.png)

You can find the list of functions [here](https://github.com/hundredrabbits/ronin/), you can find the declaration themselves [here](https://github.com/hundredrabbits/Ronin/blob/master/scripts/library.js).

**Comment by whatacold** [comment]
Thanks for the quick implementation of `(files)`.

I'm sorry, but I'm a bit confused about how to use it, is it right to drag the target images one by one to the canvas, and then run the whole lisp script?

**Comment by whatacold** [comment]
I'm also wondering if you would like to add a feature of eval'ing the last s-expr before the cursor :)

For example:

    (debug "hello")
    | ; <- the cursor is here
    (debug "world")

So that if I click that menu or press the shortcut, it only print `"hello"` to the console.
I think it helps to make the lisp script incrementally.

**Comment by neauoire** [comment]
> is it right to drag the target images one by one to the canvas, and then run the whole lisp script?

You can drag all of them at once, and cycle through them with `(export)`.

```
(clear)

(defn resize-file 
  (name index) 
  (do 
    (open name 0.5) 
    (fill 
      (circle 50 50 20) "red") 
    (export)))

(each 
  (files) resize-file)
```

> I'm also wondering if you would like to add a feature of eval'ing the last s-expr before the cursor :)

I've added eval selection with `alt+enter`

**Comment by whatacold** [comment]
This is so cool, thank you very much!
