### ISSUE TITLE
Text doesn't appear to work

### ISSUE THREAD

**Issue by jonrandy** [hundredrabbits/Ronin#133]
I've tried the demos in both Firefox and Chrome, and drawing text doesn't appear to work

**Comment by blad** [comment]
@jonrandy Text is a shape and requires that it be passed to the `fill` or `stroke` functions for it to be painted on the screen.

```lisp
(fill (text 0 40 40 "Hello") "black")
(stroke (text 0 80 40 "Hello") "black")
```

![draw-text](https://user-images.githubusercontent.com/2012909/90783072-3ee74500-e2c5-11ea-8566-168301a08fce.png)

**Comment by jonrandy** [comment]
Ok, I'll try it. Just found it odd that the demos featuring text don't work
