### ISSUE TITLE
Help showing very long content but without wrap or h-scrollbar

### ISSUE THREAD

**Issue by haxpor** [hundredrabbits/Ronin#14]
Some of example commands as shown in help page are very long.
They're cropped because there's no word-wrap, and h-scrollbar is hidden.

**Comment by neauoire** [comment]
Right. I will improve this, instead of opening in a new window, I will make it a modal.

**Comment by neauoire** [comment]
.. didn't mean to close it.

**Comment by neauoire** [comment]
Did done it.

**Comment by haxpor** [comment]
Thanks!

**Comment by haxpor** [comment]
By the way, I saw you removed out the example commands. I think for me that is critical to know how to draw arc (M..., A....), and follow examples. Just my opinion.

**Comment by neauoire** [comment]
type:

- vector circle
