### ISSUE TITLE
Pressing 'Enter' on the help screen prevents closing the help screen with 'Escape'

### ISSUE THREAD

**Issue by jakofranko** [hundredrabbits/Ronin#16]
When Ronin is being served by the Python script, typing `?` in the command prompt will show the help screen in the same window. 

This fires `commander.passive()`, which shows the help screen. Pressing `enter` will close the command prompt and clear out the input element (`commander.hide()`). As the `listen_onkeyup()` function continues, it then fires `commander.passive()` again, but this time there is no command in the command line, so there is no `key` set on line 50 of `commander.js`. `commander.passive()` clears out `ronin.module` on line 53 of `commander.js` and then tries to find a module by the key. Since this doesn't exist any more, it leaves `ronin.module` null.

Trying to press `escape` after this will do nothing, since `ronin.module` no longer routes the escape key to the help module.

I was going to create a PR for this but realized there are lots of ways you could fix it and I wasn't sure the best method. You could lock the command prompt to open, you could prevent `ronin.module` being nulled if a `ronin.module_lock` var was set, you could try to detect if the help screen was open and then just always have escape hide it if that's the case...

**Comment by neauoire** [comment]
I'm working on using the terminal log to display the help and flattened files.

**Comment by jakofranko** [comment]
Ok cool, this can probably be closed then...
