### ISSUE TITLE
no license terms

### ISSUE THREAD

**Issue by apotheon** [hundredrabbits/Ronin#19]
I have not found anything about license terms for this software.  Can I even legally use it?

Please add a license, preferably one of the [copyfree licenses](http://copyfree.org/standard/licenses) so I can be sure I can actually use it everywhere.

Thanks.

**Comment by neauoire** [comment]
Of course :) I will add a license in a bit. But use it as you will without worries in the meantime ^^

**Comment by apotheon** [comment]
I really appreciate your attention to this.  Thank. you.

**Comment by neauoire** [comment]
Added :)
