### ISSUE TITLE
How to use/download/dev?

### ISSUE THREAD

**Issue by Godje** [hundredrabbits/Ronin#20]
I am super hyped about this app, but I have no idea how to use it.
How do build it. How to run it.
There is no explanation, if there should be, anyways.
How?

**Comment by EduardoHi** [comment]
Download node.js, if the version does not come with npm download it too. Then in the directory, open Command Line/ Terminal. Run the command `npm install` after its finished run `npm start`. Any doubts let me know

**Comment by Godje** [comment]
@EduardoHi my version seems to be different from the one on the video. On the video they have like 9 tools, when I have only 6: `brush frame line io path magnet`.
I don't have most of the functions and the first feature that they show doesn't work (using mouse to feed position). It is obvious that my Ronin is outdated, even though i `cloned` the repo and ran `npm install` and `npm start`, like you said.

**Comment by neauoire** [comment]
I'm currently rebuilding Ronin as an Electron app. Give me a few more days  and I will have downloadable files :)

**Comment by neauoire** [comment]
You can now download builds for all platforms here: https://hundredrabbits.itch.io/ronin
