### ISSUE TITLE
not open source

### ISSUE THREAD

**Issue by apotheon** [hundredrabbits/Ronin#21]
The description in the README says this is open source software, but CC-BY-NC-SA is not an open source license.  (It is not even recommended for software use by Creative Commons.)

**Comment by neauoire** [comment]
Oh wow, you're so right.
It's an old license I've been using over and over again from the days when I released music source files and wanted to protect me against people who re-released the sources for money. I will migrate all these projects to MIT. Thank you for pointing this out.

**Comment by apotheon** [comment]
I really appreciate that.  Few licenses are as nice as the MIT License.
