### ISSUE TITLE
Video to help explain what Ronin is

### ISSUE THREAD

**Issue by pdurbin** [hundredrabbits/Ronin#23]
I just head about Ronin at https://botbot.me/freenode/opensourcedesign/msg/93706802/ but even after looking at the README and the website I was still confused about what it is exactly. I searched a bit more and found https://www.youtube.com/watch?v=gifzjhyBwOc (Capsule 5: Ronin Tutorial) which seems like a decent introduction. Perhaps you should link to that video (or another) from the README. It seems like an interesting tool.

**Comment by neauoire** [comment]
Hey :) I should actually redo a new Ronin introduction video.
The syntax has changed a bit. It's what I use to create/resize/export my graphics, I'd be happy to answer any question in the meantime, if you have any.

**Comment by quinnjn** [comment]
Would love to see some action on this. I tried to pull down master to play with it, but I'm a little confused on how to use it. It looks like the project has diverged since the [Ronin Tutorial video](https://www.youtube.com/watch?v=gifzjhyBwOc).

Love your work!

**Comment by neauoire** [comment]
I'm spread pretty thin at the moment, I hope to revisit this soon.

**Comment by pdurbin** [comment]
I just watched the video again and Ronin still seems like an interesting tool.

**Comment by quinnjn** [comment]
@neauoire Thanks for the [updated tutorial video](https://www.youtube.com/watch?v=SgAWGh1s9zg) you guys are amazing!

**Comment by neauoire** [comment]
✊

**Comment by pdurbin** [comment]
@quinnjn thanks for sharing the new video and thank you to whoever made it! Very interesting! I see it's linked from the README, which is perfect.
