### ISSUE TITLE
Magnet is broken

### ISSUE THREAD

**Issue by jaspertravers** [hundredrabbits/Ronin#24]
`/sources/scripts/modules/magnet.js` appears to be broken.

The line `ronin.grid.draw (size, ronin.magnet.step)` appears to be broken in two ways. `size` is not set and, more importantly, `ronin.grid.draw` doesn't exist. From a little digging I'd guess you changed `ronin.grid.` to `ronin.guide` but there isn't a compatible draw method in guide. 

When I run `magnet lock: 10` in the commander errors are thrown which lead to this line, but also the cursor disappears and becomes unable to draw. Not sure how those issues are related, but here's the info.

I've currently run out of time, and wanted to drop this bit here, but I'll continue to look into it when I get some more time later. Thanks for the awesome editor.

**Comment by neauoire** [comment]
Yes! That's right, I'm kind of moving things around this week :)
I am merging it with the guide layer, this should be fixed soon.
