### ISSUE TITLE
decouple canvas processing functions from fixed canvas target

### ISSUE THREAD

**Issue by lctrt** [hundredrabbits/Ronin#45]
Currently, the surface layer is fixed to the #surface canvas. By allowing to target and create temporary layers, we could have access to more blending functions and easy drawing on guide layer

```
(layer layer1 (fill (rect 10 10 20 20) "red")
(layer layer2 (fill (rect 15 15 20 20) "blue")
(blend (
  (normal layer1 1)
  (darken layer2  0.5)
))
```

and to define guide layer drawing
```
(defn hrule (x color) (layer _guide (stroke (line x 0 x HEIGHT) 1 color))

(hrule 40 "red") ; could use theme color by default?
($hrule)
```

**Comment by neauoire** [comment]
I love it, I want to use guides for aligning photos. This will come in handy.

**Comment by neauoire** [comment]
I think that's a bit too complex for the scope of Ronin, for now anyways.
