### ISSUE TITLE
(arc x y r 0 (mul PI 2)) — Implement the arc shape

### ISSUE THREAD

**Issue by lctrt** [hundredrabbits/Ronin#47]

**Comment by neauoire** [comment]
We might have to rename the current (path) to something else.

**Comment by neauoire** [comment]
Implemented 
```
(stroke 
  (svg "M255,60 L255,60 L135,180 L75,60 L195,210 L120,225 L105,225 L165,255 L225,195 L255,135 L285,150") 
    2 "red")
```

**Comment by lctrt** [comment]
@neauoire the current path is just returning the value at the moment, we could do without this

**Comment by neauoire** [comment]
I agree, but we need to correct the cursor helper that replaces ($path) with the dragged file.

**Comment by lctrt** [comment]
ah if we have ($path) I'd prefer keeping it then, to maintain the connection helper -> code. But I think it could still have its use if we let path do some of the work (like maybe transforming ~/ to the proper path)

**Comment by neauoire** [comment]
okay, let's keep it as a type for now then :)

**Comment by neauoire** [comment]
remove the path type, the name is now free.

**Comment by neauoire** [comment]
Implemented
