### ISSUE TITLE
shortcut for fullscreen canvas ?

### ISSUE THREAD

**Issue by ragekit** [hundredrabbits/Ronin#5]
Can it be interesting to add that ?

Also full screen seem to not be full window. 

I can check

**Comment by neauoire** [comment]
do you mean like, resizing the canvas to the window size?

**Comment by neauoire** [comment]
maybe a new unit that is a % of the window viewport would be nice, and start a new page with that setting in place.

**Comment by ragekit** [comment]
oh, 100w is not fill page width ?

**Comment by neauoire** [comment]
it's 100% of current canvas width. It's not really clear, I think there has
to be a better solution..

**Comment by ragekit** [comment]
you can resize the canvas to get the window size sadly it erases it. Its the problem with immediate mode rendering. Solution : keep in memory the drawing ops and redraw when the canvas gets "dirty" (resized or any other op that erases it)

**Comment by ragekit** [comment]
if i have time one day for the webgl port ill look into it.

**Comment by neauoire** [comment]
ah yeah, once I have the ^ translation module done, I will do the resizing through it, it will preserve the image data.

**Comment by neauoire** [comment]
Resize currently keeps the canvas content :)
Can I close this issue?

**Comment by ragekit** [comment]
its old but : yup
