### ISSUE TITLE
(translate (rect) (line)) — Cut pixels and move them somewhere else

### ISSUE THREAD

**Issue by neauoire** [hundredrabbits/Ronin#52]

**Comment by lctrt** [comment]
@neauoire  added `(translate (rect) (pos))`, simpler to implement, might be good enough / more precise than with (line). This was also the occasion to implement a prelude.lisp.

Example of use is in glitch.lisp

**Comment by neauoire** [comment]
I like it, let's move as MUCH as we can into prelude.
