### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by neauoire** [hundredrabbits/Ronin#53]

**Comment by lctrt** [comment]
is this prompted by the docstrings? regardless, I was thinking we should be able to display them in an helpful way- and use similar technique for javascript implemented functions

```
const fn = a => a + 1;
fn.help = "some docstring"
console.log(fn.help) // some docstring
```

non tested possible implementation:
```
function withDocs = (docstring, function) => {
function.docstring = docstring
return function
}
```

**Comment by neauoire** [comment]
Someone asked me if there was a documentation of the library and there isn't it would be nice if the readme had a list of the functions and their parameters.

**Comment by lctrt** [comment]
Ah yes! I'm thinking too far for now, a static doc would be essential

**Comment by lctrt** [comment]
https://github.com/hundredrabbits/Ronin/blob/master/documentation.md

**Comment by lctrt** [comment]
There's now a list of current existing functions, would be great to add more details and examples

**Comment by neauoire** [comment]
Added documentation tool :)

```
ronin.commander.docs.toMarkdown()
```
