### ISSUE TITLE
Language design goals

### ISSUE THREAD

**Issue by lctrt** [hundredrabbits/Ronin#54]
To help further development, it would be beneficial to discuss where we want to go with the language. 

Here's a few ideas:

* getting rid of callbacks in the base functions
Callbacks are useful for users, but we should not have them in functions like draw or open - which means we need to find a way to handle async functions in a synchronous way. Outside of code clarity, this would allow to keep most code in a stack. Keeping code in a stack would make it easier to create helper tools that simply add a line to it, with undo/redo/cherrypicking.
* handling async
as said in previous block, I expect this to be important/useful but hard to implement.
* separating the graphic function and the core language
Structuring the code this way should make it easier to read and contribute as the feature set grows
* Core language can be technical, graphic functions needs to stay intuitive
Having a strong core language will allow the crazier stuff to exist, but we need to keep simple use cases simple to write
* Having a "prelude" lisp library
We could now write a lot of the upcoming functions by composing the existing "native" ones, then load that set of lisp code via (include)

**Comment by neauoire** [comment]
- These are good points, I don't know how to resolve the async issues technically, so I don't mind the callback workaround for now. But yeah, it would be nice if it wasn't necessary.

Actually, it would be nice to start getting rid of some of the library functions that can be easily replicated in lisp, and start running them as includes. We can start building a library folder of these. :)

**Comment by AAorris** [comment]
What if we returned promises and offered something like await using `Promise.all(...)`?

```lisp
(await
  ((open a) (open b))
  (lambda (a b)
     ((draw a)
      (draw b)
      (save c))))
``` 

```javascript
const setup = [open(a), open(b)]
const loaded = (a, b) => {
  draw(a)
  draw(b)
  save(c)
}
Promise.all(setup).then(loaded)
```

**Comment by lctrt** [comment]
@AAorris this look like this could be done, but I'm not sure it would cover all cases, as it would not handle this case

```lisp
(await
  ((open a) (open b))
  (lambda (a b)
     ((draw a)
      (await (open c) (lambda (c) (draw c)))
      (save c))))
```

**Comment by xvw** [comment]
Why not masking async stuff and pretend that everything is sync, except what it should be explicitely async?

**Comment by lctrt** [comment]
@xvw that's what I'd prefer as well, this will need some refactoring of the interpreter but would be great

**Comment by xvw** [comment]
Yes, every step should be the continuation of the previous.

**Comment by lctrt** [comment]
@xvw I found a way to do this, I'll finish and PR tonight :)

**Comment by neauoire** [comment]
I like the current handling of async done in the background, so we don't have to think about it when writing ronin lisp. o/
