### ISSUE TITLE
(when (key-down "rightArrow") (echo "hello")) — Implement key triggers in animate mode

### ISSUE THREAD

**Issue by neauoire** [hundredrabbits/Ronin#55]

**Comment by neauoire** [comment]
That may or may not open a seccond set of floodgates.

**Comment by lctrt** [comment]
Pong in Ronin in 3..2..1..

**Comment by cauli** [comment]
proposal:

```
(on (key-down "a") fn)
(on (key-down "cmd+shift+a") fn)
(on (key-down "alt+A") fn)
(on (key-down "left") fn)
(on (key-down "up") fn)
(on (key-down "pageup") fn)
```

**Comment by neauoire** [comment]
I think whenever a key is pressed and the focus is not on the commander, it should add the whole event's name in the bindings. So you can get things like `key`, and `keyCode`, and `ctrl`..

**Comment by cauli** [comment]
Ok. Something like this? 

```
(defn do-something 
  (e) 
  (if 
    (eq e:key "ArrowRight")
    (echo "→")))

(on "key-up" do-something)
```

**Comment by neauoire** [comment]
Exactly

**Comment by cauli** [comment]
Pong is coming.
![pong](https://user-images.githubusercontent.com/284283/62086519-dd3dde00-b25e-11e9-9e57-c3887f9001aa.gif)

**Comment by neauoire** [comment]
No, way haha.

**Comment by lainsce** [comment]
The first hidden game on Ronin :stuck_out_tongue_winking_eye:

**Comment by neauoire** [comment]
Good enough
