### ISSUE TITLE
{:key 1 :b 2} - objects 

### ISSUE THREAD

**Issue by lctrt** [hundredrabbits/Ronin#57]
currently we have ways to get data from objects but no way to create them. These would be useful to set option in other functions.

```
(def foo {:a 1 :b 2}) ; equivalent to const foo = {a: 1, b: 2} in JS
:a ; should be a new type TYPES.symbol
(:a foo) ; returns 1
(:c foo 4) ; returns default value 4
(:y (rect 1 2 3 4)) ; returns 2

(process {:contrast 0.5 :brightness -0.5})
(rect 5 5 15 15 {:border-radius 4})
```

**Comment by neauoire** [comment]
I agree, I love using these kinds of data structures.

**Comment by xvw** [comment]
Agreed too, but I think that, instead of some "exception" in grammar, we should use a functional approach for accessor/mutator:

```scheme
(get :a foo) 
(set :a foo 10) -- returns a copy of foo where :a is set to 10
```

**Comment by lctrt** [comment]
@xvw when you say exception, you mean the `(:a foo)`? it's not needed but I like how easy it is to use. In Clojure if I remember right there's the same both way `(:a foo)` and `(foo :a)`.

**Comment by neauoire** [comment]
Can't we just 

```
  this.get = (item, key) => {
    return item[key]
  }

  this.set = (item, key, val) => {
    item[key] = val
    return item[key]
  }
```

**Comment by xvw** [comment]
@neauoire yep, I think it is better, and I like the syntaxe of @lctrt to describe product types.

**Comment by neauoire** [comment]
I'll remove `(of)` that was just a placeholder, and I'll migrate the examples

**Comment by lctrt** [comment]
@neauoire if we can have `(get)` with the current code of `(of)`. 

current `(of)` implementation looks more complex
```
this.of = (h, ...keys) => {
    return keys.reduce((acc, key) => {
      return acc[key]
    }, h)
  }
```
but it allows more flexibility:
```
; shape = { rect: { x: 1, y: 2} }
(of shapes "rect" "x") ; returns 1
; rect = {x:1,y:2}
(of rect "x") ; returns 1
```

**Comment by neauoire** [comment]
yeah I noticed that `(of)` was able to tunnel through objects, maybe the name should reflect that.

**Comment by lctrt** [comment]
will start object support now. Before adding support for the nice `{}` syntax I'll need to add a more basic `(obj)` that can then be sugared to `{}`

**Comment by lctrt** [comment]
All done, with {} and :foo syntax available :) example objects.lisp demonstrate the syntax
