### ISSUE TITLE
Stop animation on new file/load file.

### ISSUE THREAD

**Issue by neauoire** [hundredrabbits/Ronin#65]

**Comment by ngradwohl** [comment]
I also noticed that a program in animation mode doesn't stop when it is run again - it continues to run in the background forever. 
That's especially bad in a livecoding setup, becuse when you edit and rerun the current program Ronin gets slower and slower.

**Comment by neauoire** [comment]
Yeah, I haven't found a solution for that yet.

**Comment by ngradwohl** [comment]
I just raised pull to fix the main loop issue in anim mode

**Comment by neauoire** [comment]
Testing now.

**Comment by neauoire** [comment]
Working :)
