### ISSUE TITLE
error start Ronin 64 windows 8.1

### ISSUE THREAD

**Issue by catafest** [hundredrabbits/Ronin#73]
​I got errors when I try to run the ronin-windows-64.zip64 MB with Windows 8.1 NVIDIA 740M
See the error:
​https://imgur.com/a/rxH6ooQ​
I used windows 8.1 , NVIDIA 740M 

​

**Comment by neauoire** [comment]
error loading the error report:
<img width="721" alt="Screen Shot 2019-07-22 at 8 41 42 PM" src="https://user-images.githubusercontent.com/1455726/61629897-2d49fd00-acc1-11e9-938f-b91bfe7c9b58.png">
I used the latest Firefox

**Comment by neauoire** [comment]
Looking at [this url](https://imgur.com/a/rxH6ooQ), I see the error. 
And that is from the Itch build?

I cannot reproduce this error on OSX or Linux, let me see if I can find someone else on Windows who can help.

**Comment by msarchet** [comment]
Hi yeah I ran into this error too on the itch build. On Windows 10.

I pulled the repo and tried to build locally and ran into a problem with node-gyp bindings trying to target the wrong version and I'm currently working on sorting that out

my error right now is like this

```
Error: gyp info it worked if it ends with ok
gyp info using node-gyp@4.0.0
gyp info using node@8.9.3 | win32 | x64
gyp info spawn C:\Python27\python.exe
gyp info spawn args [ 'C:\\Users\\msarc\\code\\ronin\\desktop\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-G',
gyp info spawn args   'msvs_version=2015',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\msarc\\code\\ronin\\desktop\\node_modules\\@serialport\\bindings\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\msarc\\code\\ronin\\desktop\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\msarc\\.electron-gyp\\5.0.7\\include\\node\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\msarc\\.electron-gyp\\5.0.7',
gyp info spawn args   '-Dnode_gyp_dir=C:\\Users\\msarc\\code\\ronin\\desktop\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=C:\\Users\\msarc\\.electron-gyp\\5.0.7\\<(target_arch)\\node.lib',
gyp info spawn args   '-Dmodule_root_dir=C:\\Users\\msarc\\code\\ronin\\desktop\\node_modules\\@serialport\\bindings',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'C:\\Users\\msarc\\code\\ronin\\desktop\\node_modules\\@serialport\\bindings\\build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\15.0\Bin\MSBuild.exe
gyp info spawn args [ 'build/binding.sln',
gyp info spawn args   '/clp:Verbosity=minimal',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=x64' ]
gyp ERR! UNCAUGHT EXCEPTION
gyp ERR! stack Error: spawn C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\15.0\Bin\MSBuild.exe ENOENT
gyp ERR! stack     at _errnoException (util.js:1024:11)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
gyp ERR! stack     at onErrorNT (internal/child_process.js:372:16)
gyp ERR! stack     at _combinedTickCallback (internal/process/next_tick.js:138:11)
gyp ERR! stack     at process._tickCallback (internal/process/next_tick.js:180:9)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\msarc\\code\\ronin\\desktop\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--target=5.0.7" "--arch=x64" "--dist-url=https://electronjs.org/headers" "--build-from-source"
gyp ERR! cwd C:\Users\msarc\code\ronin\desktop\node_modules\@serialport\bindings
gyp ERR! node -v v8.9.3
gyp ERR! node-gyp -v v4.0.0
gyp ERR! This is a bug in `node-gyp`.
gyp ERR! Try to update node-gyp and file an Issue if it does not help:
gyp ERR!     <https://github.com/nodejs/node-gyp/issues>

Failed with exit code: 7
    at SafeSubscriber._error (C:\Users\msarc\code\ronin\desktop\node_modules\spawn-rx\lib\src\index.js:267:84)
    at SafeSubscriber.__tryOrUnsub (C:\Users\msarc\code\ronin\desktop\node_modules\rxjs\internal\Subscriber.js:205:16)
    at SafeSubscriber.error (C:\Users\msarc\code\ronin\desktop\node_modules\rxjs\internal\Subscriber.js:156:26)
    at Subscriber._error (C:\Users\msarc\code\ronin\desktop\node_modules\rxjs\internal\Subscriber.js:92:26)
    at Subscriber.error (C:\Users\msarc\code\ronin\desktop\node_modules\rxjs\internal\Subscriber.js:72:18)
    at MapSubscriber.Subscriber._error (C:\Users\msarc\code\ronin\desktop\node_modules\rxjs\internal\Subscriber.js:92:26)
    at MapSubscriber.Subscriber.error (C:\Users\msarc\code\ronin\desktop\node_modules\rxjs\internal\Subscriber.js:72:18)
    at SafeSubscriber._next (C:\Users\msarc\code\ronin\desktop\node_modules\spawn-rx\lib\src\index.js:242:65)
    at SafeSubscriber.__tryOrUnsub (C:\Users\msarc\code\ronin\desktop\node_modules\rxjs\internal\Subscriber.js:205:16)
    at SafeSubscriber.next (C:\Users\msarc\code\ronin\desktop\node_modules\rxjs\internal\Subscriber.js:143:22)
```

**Comment by Earthnuker** [comment]
Hi, i'm also getting error in the latest 2 itch.io builds, build number 16 appears to be the latest working version, everything after that gives me the following error:
```
Error:  A JavaScript error occurred in the main process

Uncaught Exception:
Error: \\?\C:\Users\Earthnuker\AppData\Roaming\itch\apps\Ronin\resources\app\node_modules\@serialport\bindings\build\Release\bindings.node is not a valid Win32 application.
\\?\C:\Users\Earthnuker\AppData\Roaming\itch\apps\Ronin\resources\app\node_modules\@serialport\bindings\build\Release\bindings.node
    at process.func [as dlopen] (electron/js2c/asar.js:155:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:857:18)
    at Object.func [as .node] (electron/js2c/asar.js:155:31)
    at Module.load (internal/modules/cjs/loader.js:677:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:609:12)
    at Function.Module._load (internal/modules/cjs/loader.js:601:3)
    at Module.require (internal/modules/cjs/loader.js:715:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at bindings (C:\Users\Earthnuker\AppData\Roaming\itch\apps\Ronin\resources\app\node_modules\bindings\bindings.js:112:48)
    at Object.<anonymous> (C:\Users\Earthnuker\AppData\Roaming\itch\apps\Ronin\resources\app\node_modules\@serialport\bindings\lib\win32.js:1:36)
```

looks like it's trying to load a missing/corrupt DLL file for the serial port bindings

**Comment by secretgspot** [comment]
same here. error

**Comment by neauoire** [comment]
@ngradwohl Do you know how I could build for other platforms? 
The OSC stuff is causing this error.

**Comment by neauoire** [comment]
@msarchet if you're trying to build locally, do this:

```
./node_modules/.bin/electron-rebuild
```

**Comment by ngradwohl** [comment]
is this windows 8.1 machine really a 64bit system? looks like the errors you get when you try to run a 64bit binary on a 32bit plattform

what windows version have the builds been compiled on?

**Comment by msarchet** [comment]
@ngradwohl hey my machine is this

![image](https://user-images.githubusercontent.com/399084/61677411-6760d200-acb4-11e9-99bb-cd82b5f4cb03.png)

and I'm still running into this problem. I'm gonna see if I can go back through the commit history and find a change that causes this or if it's some kind of update or something to package.json that may have specifically caused this. It's weird it looks like it just wants a different version of node-gyp? I'm not 100% sure how to get this figured out but I'm looking into it some.

**Comment by neauoire** [comment]
Start at the OSC commit.

**Comment by ngradwohl** [comment]
ok - so we have two different issues described in this bug - the first one is that the downloaded build is not starting on a win 8.1 machine 
and the second one is that the BUILD is not working on a win 10 machine because of an node-gpy error. 
Right?

**Comment by ngradwohl** [comment]
I think error no 1 is because of a missmatch between a 64bit build and a 32bit version of windows - can somebody please verify this?

**Comment by ngradwohl** [comment]
err no2 seems to be caused by a problem in node-gyp. 
please try to install it on your machine in the most recent version (5.xx if i recall correct) and install the build-tools for windows following the instructions from 
https://github.com/nodejs/node-gyp

from your error messages it looks like two different versions of node-gyp are installed on your machine for whatever reason

**Comment by ngradwohl** [comment]
@neauoire the issues definitly started with the commit of the osc build, because i had to introduce the electron-rebuild package to make sure the osc package is build against the node.js version bundled inside of electron and not any other node.js running outside of it (see https://github.com/colinbdclark/osc.js#installing-oscjs-for-use-in-electron-applications)

**Comment by msarchet** [comment]
@ngradwohl I think they are the same error with the electron bindings? After I try to launch the failed electron-rebuild version of my built app I see the same error that this issue was opened on. I suspect this has to do with the serialport package. I fixed the node-gyp issue and still have it

**Comment by ngradwohl** [comment]
@msarchet Ah! ok - the node-gyp error stacktrace confused me - so you also get the "not a valid Win32 application"-error when building from scratch now?

**Comment by neauoire** [comment]
I use `node-osc` instead of `osc` in Orca and I don't have this issue, maybe we could switch.

**Comment by msarchet** [comment]
@neauoire  I'll take a look since I'm currently digging into this.

btw it looks like electron-rebuild references node-gyp 4.0.0 directly which can't build serialport for me on windows, but if I manually build those bindings using node-gyp 5.0.6 it works for me? IDK if you can configure node-gyp to use that version. Investigating some.

**Comment by msarchet** [comment]
I have a working version with node-osc. I think I patched the osc stuff correctly I need to find an example to test. I put a pull request up in a moment. I removed electron-rebuild which seems to also fix the issue.

**Comment by neauoire** [comment]
Could someone test the latest itch build on windows?

**Comment by Earthnuker** [comment]
latest itch build (19) appears to be working fine!

**Comment by secretgspot** [comment]
> Could someone test the latest itch build on windows?

works on windows 10 64bit

**Comment by neauoire** [comment]
Amazing, thanks :)
