### ISSUE TITLE
Weirdness with rendering and OSC

### ISSUE THREAD

**Issue by VegaDeftwing** [hundredrabbits/Ronin#77]
changing the last few lines of the `on-animate` example to use OSC:
```
...
(defn redraw 
  () 
  (
    (clear) 
    (times seg-count draw-dash)))
(on "/a" redraw)
```
and then changing the code and attempting to re-render causes the sine wave to continue to be rendered until Ronin is restarted. Arch Linux, Itch, 'Version 20'

**Comment by neauoire** [comment]
Still looking into it :) sorry for the delay..

**Comment by neauoire** [comment]
I'll remove OSC for now, might revisit later :)
