### ISSUE TITLE
(:x frame) — Implement this pattern, it's very important

### ISSUE THREAD

**Issue by neauoire** [hundredrabbits/Ronin#79]

**Comment by lctrt** [comment]
YES! I can do that tonight :)

**Comment by neauoire** [comment]
amazing, I will migrate all the examples and docs.

**Comment by lctrt** [comment]
Done and pushed, spiral has an example. frame needs to stay as `(frame)` because it's a function.

**Comment by neauoire** [comment]
Okay, so I've tried something, the `(:x some-rect)` format wasn't as space efficient as I expected, so I've implemented `some-rect:x` on top of your commit, but I'm not sure if that's actually the proper way to do that, could you have a look over what I did, maybe we don't need the `(:x some-rect)` format if `some-rect:x` works. What do you think?
