### ISSUE TITLE
bunch of unexpected behavior

### ISSUE THREAD

**Issue by flowen** [hundredrabbits/Ronin#82]
he dev! 

I was playing around with it today and had some unexpected problems. I tried some basic examples but was met with errors, also got a whole bunch of loading errors. 

Not sure what it might be. 
Also had some strange behavior where I would draw a rect with only a line. Then wrote out a fill with a rect, but nothing would happen on re-render. If I cleared everything properly (no other code but `clear`) it ran fine.

![Screen Shot 2019-07-27 at 16 51 30](https://user-images.githubusercontent.com/4084169/61995953-0ad42d00-b08f-11e9-8330-0c23c6f08c39.png)
![Screen Shot 2019-07-27 at 16 51 02](https://user-images.githubusercontent.com/4084169/61995954-0ad42d00-b08f-11e9-8fd6-bfb2035934d9.png)
![Screen Shot 2019-07-27 at 16 54 26](https://user-images.githubusercontent.com/4084169/61995979-60103e80-b08f-11e9-836d-45db40663039.png) Yellow, sometimes red, became black instead.

Nothing urgent, but was just playing around and noticed these quirks. Let me know if you need any more information! 

![Screen Shot 2019-07-27 at 16 57 38](https://user-images.githubusercontent.com/4084169/61995998-abc2e800-b08f-11e9-8833-9bcfa1f58c5d.png)

Also would love to use 'tabs' for indent :)

**Comment by neauoire** [comment]
In your screenshot, notice how you're giving 10, as a color value to fill:

```
(fill 
  (rect 100 100 200 300) 10 "yellow")
```

The fill function is `(fill rect color)`, I think maybe you replaced `(stroke)` with `(fill)` and forgot to remove the light width? Maybe I should swap `(color)` to be first so this doesn't happen.. Yeah, I'll do that I think.

**Comment by neauoire** [comment]
Also added tab to indent :)

**Comment by flowen** [comment]
Ahh, yea I lazily copied&pasted stroke and changed it to fill.. got caught red-handed! 😂 but cool it gave you inspiration to add more consistency.
