### ISSUE TITLE
toward pen pressure

### ISSUE THREAD

**Issue by ragekit** [hundredrabbits/Ronin#9]
found those thqt might indicate a pen pressure api is on the way ! https://mobiforge.com/design-development/html5-pointer-events-api-combining-touch-mouse-and-pen

**Comment by ragekit** [comment]
(canary got it on chrome and hidden behind a flag for firefox https://developer.mozilla.org/fr/docs/Web/API/PointerEvent )

**Comment by neauoire** [comment]
Oh cool! Looking forward :)

**Comment by ragekit** [comment]
yeah its on chrome now ! https://www.chromestatus.com/feature/4504699138998272

**Comment by neauoire** [comment]
Mhmm, it's not working for me on the Chromebook :( Investigating.

**Comment by ragekit** [comment]
hum, mb its just for pressure sensitive touch device ? or the .pressure is not in yet :(((((

**Comment by ragekit** [comment]
tested : work but pressure is always .5 . i guess its not implemented yet

**Comment by ragekit** [comment]
oh fuck its working for me now : test here https://pressurejs.com/
