### ISSUE TITLE
CMD+R on inspect makes users lose progress

### ISSUE THREAD

**Issue by cauli** [hundredrabbits/Ronin#90]
It is common for the user to type CMD+R many times during the coding workflow, to run the code.

However, when inspecting the project (with CMD+.), if the user types CMR+R with the console focused, the browser screen will be reloaded without confirmation, causing users to lose their progress.

Possible solutions:
- Add confirmation screen before reloading 
<img width="449" alt="Screen Shot 2019-07-29 at 00 38 17" src="https://user-images.githubusercontent.com/284283/62013858-33e0e480-b199-11e9-8add-a70f02a2c314.png">

**Comment by neauoire** [comment]
That's a good point, do you know how to catch the reload fired from the console?

**Comment by cauli** [comment]
Both Chrome and Firefox will respect this snippet:

```
window.addEventListener("beforeunload", function(e) { 
  e.preventDefault();
  e.returnValue = '';
});
```

Provided the user has interacted with the page.

In more recent versions of browsers, it is not possible anymore to display a custom confirm or alert for this event. See [this](https://developer.mozilla.org/en-US/docs/Web/API/WindowEventHandlers/onbeforeunload).

Message on Chrome `75.0.3770.142`:
<img width="432" alt="Screen Shot 2019-07-29 at 09 25 35" src="https://user-images.githubusercontent.com/284283/62029458-e25d4780-b1e2-11e9-97c4-df8131731444.png">

**Comment by neauoire** [comment]
Would you like to make a PR?

**Comment by cauli** [comment]
Yes. I'll try to do it in a couple of days.

Took a quick look at the electron documentation and they seem to have custom wrapper for those events.

It may be possible to use:
`will-prevent-unload`, `contents.isDevToolsOpened()`, also `devtools-reload-page'

Maybe the simplest solution is to use `event.preventDefault()` on `devtools-reload-page`.

Ref:
- https://electronjs.org/docs/api/web-contents
