### ISSUE TITLE
Too easy to accidently target the whole canvas with (pixels), very slow

### ISSUE THREAD

**Issue by radgeRayden** [hundredrabbits/Ronin#97]
Very often when I'm trying out the pixels function I accidently leave the rect parameter out which causes it to apply to the whole canvas. Unfortunately this is very slow and stalls the editor until the operation is complete, so I have to wait up to 30 seconds until I can do anything again. This could be fixed by taking out the default initialization on the rect parameter, so if we want to do it to the whole area we need to be explicit about it.

**Comment by neauoire** [comment]
Is it possible that you're running an old version?

**Comment by radgeRayden** [comment]
I am using the itchio version, it seems to have been fixed in between my initial complaint and now (or at least that's when I got a different update).

**Comment by neauoire** [comment]
awesome :) I'm glad to hear it's fixed.
